// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2X2Eevh5LXXUTUlS2VUjxRAh853Q7x5I',
    appId: '1:1028068402405:web:b5d90a311415b85f5ae00c',
    messagingSenderId: '1028068402405',
    projectId: 'money-expense-tracker-dab32',
    authDomain: 'money-expense-tracker-dab32.firebaseapp.com',
    storageBucket: 'money-expense-tracker-dab32.firebasestorage.app',
    measurementId: 'G-6356RYNE2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdbjx2muWiUVZ5xOwoorZ9oJHYAmY75-s',
    appId: '1:1028068402405:android:54ed3ca19b4d8e685ae00c',
    messagingSenderId: '1028068402405',
    projectId: 'money-expense-tracker-dab32',
    storageBucket: 'money-expense-tracker-dab32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCOr0fzh2TPpPJxujlsMLzYJxUdwrEYLY',
    appId: '1:1028068402405:ios:80872dabe80a878e5ae00c',
    messagingSenderId: '1028068402405',
    projectId: 'money-expense-tracker-dab32',
    storageBucket: 'money-expense-tracker-dab32.firebasestorage.app',
    iosClientId: '1028068402405-jpid9p93198e8dfj38mmttdohgkv0p0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.money',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCOr0fzh2TPpPJxujlsMLzYJxUdwrEYLY',
    appId: '1:1028068402405:ios:80872dabe80a878e5ae00c',
    messagingSenderId: '1028068402405',
    projectId: 'money-expense-tracker-dab32',
    storageBucket: 'money-expense-tracker-dab32.firebasestorage.app',
    iosClientId: '1028068402405-jpid9p93198e8dfj38mmttdohgkv0p0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.money',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2X2Eevh5LXXUTUlS2VUjxRAh853Q7x5I',
    appId: '1:1028068402405:web:e0094ef3fa6edce55ae00c',
    messagingSenderId: '1028068402405',
    projectId: 'money-expense-tracker-dab32',
    authDomain: 'money-expense-tracker-dab32.firebaseapp.com',
    storageBucket: 'money-expense-tracker-dab32.firebasestorage.app',
    measurementId: 'G-2HVFPT4YH4',
  );

}